# Generated by Django 4.1.3 on 2022-12-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_loginmodel_signupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
        migrations.DeleteModel(
            name='SignupModel',
        ),
    ]
