# Generated by Django 4.1.3 on 2022-12-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_loginmodel_password_alter_signupmodel_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
