# Generated by Django 4.1.3 on 2022-12-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_password1_signupmodel_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
