# Generated by Django 4.1.3 on 2022-12-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_signupmodel_phone_signupmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='name',
        ),
    ]
