# Generated by Django 4.1.3 on 2022-12-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customermodel_loginmodel_rename_cart_cartmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
